apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-metrics-conf
data:
  metrics.conf: |
    server {
        listen 8080;
        location /stub_status {
            stub_status;
            allow all;
        }
    }